on: push
name: Main
jobs:
  lint-and-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Build
      uses: CultureHQ/actions-yarn@master
      with:
        args: build
